name: demo
model: MACE
train_file: ./demo_train.xyz
valid_fraction: 0.1
checkpoints_dir: ./ckps
log_dir: ./logs
results_dir: ./logs
model_dir: ./logs
seed: 42
E0s: average
batch_size: 10
correlation: 3
default_dtype: float32
device: cuda
ema: true
ema_decay: 0.99
energy_key: energy
energy_weight: 10
error_table: TotalMAE
eval_interval: 2
forces_key: forces
forces_weight: 10
loss: weighted
lr: 1e-3
max_L: 2
max_num_epochs: 400
num_channels: 256
num_interactions: 2
optimizer: adamw
patience: 10
r_max: 6
swa: true
start_swa: 100
#distributed: yes
enable_cueq: yes
restart_latest: yes
